apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: warden-storage
  labels:
    app: redis
    tier: storage
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: warden-cache-redis
  namespace: warden-storage
  labels:
    app: redis
    tier: storage
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: warden-storage
  labels:
    app: redis-sentinel
    tier: storage
spec:
  type: ClusterIP
  ports:
  - port: 26379
    targetPort: 26379
    name: sentinel
  selector:
    app: redis-sentinel
