apiVersion: apps/v1
kind: Deployment
metadata:
  name: warden-redis-sentinel
  namespace: warden-storage
  labels:
    app: redis-sentinel
    tier: storage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
        tier: storage
    spec:
      containers:
      - name: sentinel
        image: redis:7.2.4-alpine
        command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
        ports:
        - containerPort: 26379
          name: sentinel
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: sentinel-config
          mountPath: /etc/redis
        livenessProbe:
          exec:
            command: ["redis-cli", "-p", "26379", "ping"]
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command: ["redis-cli", "-p", "26379", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
      volumes:
      - name: sentinel-config
        configMap:
          name: sentinel-config
